# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoUnitColorizer
                                 A QGIS plugin
 Color geologic units
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-16
        copyright            : (C) 2025 by savage13
        email                : savage@uri.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoUnitColorizer class from file GeoUnitColorizer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_unit_colorizer import GeoUnitColorizer
    return GeoUnitColorizer(iface)
